LeilaoOnline/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using LeilaoOnline.Areas.HelpPage.ModelDescriptions;
using LeilaoOnline.Areas.HelpPage.Models;

namespace LeilaoOnline.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

LeilaoOnline/Controllers/LeilaoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using LeilaoOnline.Models;

namespace LeilaoOnline.Controllers
{

    [Authorize]
    public class LeilaoController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var leiloes = _db.Leiloes.Include(l => l.Responsavel).Include(l => l.Status);

            return View(leiloes.ToList());
        }

        [Authorize(Roles = "Usuario")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leilao leilao = _db.Leiloes.Find(id);
            if (leilao == null)
            {
                return HttpNotFound();
            }
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome");
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome");

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,ValorInicial,Usado,DataAbertura,DataFim,ResponsavelId,StatusId")] Leilao leilao)
        {
            if (ModelState.IsValid)
            {
                leilao.Id = Guid.NewGuid();

                _db.Leiloes.Add(leilao);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome", leilao.ResponsavelId);
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome", leilao.StatusId);
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leilao leilao = _db.Leiloes.Find(id);
            if (leilao == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome", leilao.ResponsavelId);
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome", leilao.StatusId);
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,ValorInicial,Usado,DataAbertura,DataFim,ResponsavelId,StatusId")] Leilao leilao)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(leilao).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome", leilao.ResponsavelId);
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome", leilao.StatusId);
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leilao leilao = _db.Leiloes.Find(id);
            if (leilao == null)
            {
                return HttpNotFound();
            }
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Leilao leilao = _db.Leiloes.Find(id);
            _db.Leiloes.Remove(leilao);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeilaoOnline/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="container">
        <h5>Contate-nos - todos os dias - +55 31 9 9999-9999</h5>
        <div class="row">
            <div class="col-lg-4">
                <span>
                    <a href="#" class="social-icon si-dark si-facebook si-dark-round">
                        <i class="fa fa-facebook"></i>
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a href="#" class="social-icon si-dark si-twitter si-dark-round">
                        <i class="fa fa-twitter"></i>
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a href="#" class="social-icon si-dark si-g-plus si-dark-round">
                        <i class="fa fa-google-plus"></i>
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a href="#" class="social-icon si-dark si-skype si-dark-round">
                        <i class="fa fa-skype"></i>
                        <i class="fa fa-skype"></i>
                    </a>
                </span>
            </div>
            <div class="col-lg-8 text-right">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="#">Sobre</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Novidades</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Termos & Condições</a>
                    </li>
                    <li class="list-inline-item">
                        &copy; Copyright @DateTime.Now.Year. Todos direitos reservados. Leilão On-Line
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

LeilaoOnline/Views/Shared/_FooterAdmin.cshtml
<footer class="content-footer bg-light b-t">
    <div class="d-flex flex align-items-center pl-15 pr-15">
        <div class="d-flex flex p-3 ml-auto">
            <div>
                Versão - 1.0
            </div>
        </div>
        <div class="d-flex flex p-3 mr-auto justify-content-end">
            <div class="text-muted">© Copyright @DateTime.Now.Year. Cheirinho do Campo</div>
        </div>
    </div>
</footer>

LeilaoOnline/Views/Shared/_HeaderAdmin.cshtml
@using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
{
    @Html.AntiForgeryToken()
}

<header class="navbar page-header whiteHeader navbar-expand-lg">
    <ul class="nav flex-row mr-auto">
        <li class="nav-item">
            <a href="javascript:void(0)" class="nav-link sidenav-btn h-lg-down">
                <span class="navbar-toggler-icon"></span>
            </a>
            <a class="nav-link sidenav-btn h-lg-up" href="#page-aside" data-toggle="dropdown" data-target="#page-aside">
                <span class="navbar-toggler-icon"></span>
            </a>
        </li>
    </ul>
    <ul class="nav flex-row order-lg-2 ml-auto nav-icons">
        <li class="nav-item dropdown user-dropdown align-items-center">
            <a class="nav-link" href="#" id="dropdown-user" role="button" data-toggle="dropdown">
                <span class="user-states states-online">
                    @*<img src="images/avatar6.jpg" width="35" alt="" class=" img-fluid rounded-circle">*@
                </span>
                <span class="ml-2 h-lg-down dropdown-toggle" style="text-transform: none;">
                    @User.Identity.Name
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-user">
                <div class="text-center p-3 pt-0 b-b mb-5">
                    <span class="mb-0 d-block font300 text-title fs-1x"><span class="font700">@User.Identity.Name</span></span>
                    <span class="fs12 mb-0 text-muted">@(User.IsInRole("Admin") ? "Administrator" : "Usuário")</span>
                </div>
                @if (Request.IsAuthenticated && !User.IsInRole("Admin"))
                {
                    <a class="dropdown-item" href="@Url.Action("MeusDados", "Admin")"><i class="icon-User"></i> Meus Dados</a>
                }
                <a class="dropdown-item" href="http://mail5011.smarterasp.net/Login.aspx" target="_blank"><i class="icon-Envelope"></i> Email</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="@Url.Action("ChangePassword", "Manage")"><i class="icon-Key"></i> Trocar Senha</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()"><i class="icon-Power"></i> Sair</a>
            </div>
        </li>
        <li class="h-lg-up nav-item">
            <a href="#" class=" nav-link collapsed" data-toggle="collapse" data-target="#navbarToggler" aria-expanded="false">
                <i class="icon-Magnifi-Glass2"></i>
            </a>
        </li>
    </ul>
</header>

LeilaoOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @if (string.IsNullOrEmpty(@ViewBag.Title))
    {
        <title>Leilão On-Line</title>
    }
    else
    {
        <title>@ViewBag.Title - Leilão On-Line</title>
    }

    <!-- Bootstrap-->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/bootstrap/dist/css/bootstrap.css">

    <!-- Plugins CSS -->
    <link rel="stylesheet" href="@Url.Content("~/Theme/law-firm/html/css/plugins/plugins.css")">
    <link rel="stylesheet" href="@Url.Content("~/Theme/law-firm/html/linearicons/fonts.css")">
    <link rel="stylesheet" href="@Url.Content("~/Theme/law-firm/html/css/style.css")">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Theme/law-firm/html/smart-form/contact/css/smart-forms.css")">

    <!-- Data Tables -->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/data-tables/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/data-tables/responsive.bootstrap4.min.css">
</head>

<body>

    <!-- Preloader -->
    <div id="preloader">
        <div id="preloader-inner"></div>
    </div>

    @Html.Partial("_Menu")

    @RenderBody()

    @Html.Partial("_Footer")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/inputmask")
    @*@Scripts.Render("~/bundles/jqueryval")*@

    @RenderSection("styles", required: false)
    @RenderSection("scripts", required: false)

    <!-- Bback to Top-->
    <a href="#" class="back-to-top" id="back-to-top"><i class="icon-chevron-up"></i></a>

    <!-- jQuery First, then Tether, then Bootstrap JS. -->
    <script type="text/javascript" src="@Url.Content("~/Theme/law-firm/html/js/plugins/plugins.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Theme/law-firm/html/js/law-firm.custom.js")"></script>

    <!--smart-form script-->
    <script type="text/javascript" src="@Url.Content("~/Theme/law-firm/html/smart-form/contact/js/jquery.form.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Theme/law-firm/html/smart-form/contact/js/jquery.validate.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Theme/law-firm/html/smart-form/contact/js/additional-methods.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Theme/law-firm/html/smart-form/contact/js/smart-form.js")"></script>

    <!-- Data Tables -->
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/responsive.bootstrap4.min.js"></script>
    <script src="~/Theme/admin-dashboardUi/html/js/plugins-custom/datatables-custom.js"></script>

    <!-- RECAPTCHA GOOGLE -->
    <script src='https://www.google.com/recaptcha/api.js'></script>

    <script type="text/javascript">

        $(document).ready(function ($) {

            $("#logout").click(function (e) {
                e.preventDefault();

                var authorization = sessionStorage.getItem('token_type') + " " + sessionStorage.getItem('access_token');

                $.ajax({
                    type: 'POST',
                    url: '/api/Account/Logout',
                    dataType: 'jsonp',
                    contentType: 'application/json',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': authorization
                    },
                    success: function () {
                        sessionStorage.removeItem('access_token');
                        sessionStorage.removeItem('token_type');
                        sessionStorage.removeItem('expires_in');
                        sessionStorage.removeItem('userName');
                        sessionStorage.removeItem('issued');
                        sessionStorage.removeItem('expires');

                        window.location.href = '@Url.Action("Index","Home")';
                    },
                    error: function (result) {
                        alert(JSON.stringify(result));
                    }
                });

                sessionStorage.removeItem('access_token');
                sessionStorage.removeItem('token_type');
                sessionStorage.removeItem('expires_in');
                sessionStorage.removeItem('userName');
                sessionStorage.removeItem('issued');
                sessionStorage.removeItem('expires');

                window.location.href = '@Url.Action("Index","Home")';
            });

        });

    </script>
</body>
</html>

LeilaoOnline/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("styles", required: false)
    @RenderSection("scripts", required: false)
</body>
</html>

LeilaoOnline/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - Cheirinho do Campo</title>

    <!-- Bootstrap-->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/bootstrap/dist/css/bootstrap.css">

    <!--Common Plugins CSS -->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/css/plugins/plugins.css">

    <!--fonts-->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/line-icons/line-icons.css">
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/font-awesome/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/chartist/chartist.min.css" />
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/css/chartist-custom.css" />

    <!-- jvectormap -->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/vector-map/jquery-jvectormap-2.0.2.css" />
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/css/style.css">

    <!-- Data Tables -->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/data-tables/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/data-tables/responsive.bootstrap4.min.css">

    <!-- DATE PICKER -->
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/lib/dt-picker/jquery.datetimepicker.min.css">
    <link rel="stylesheet" href="~/Theme/admin-dashboardUi/html/css/picker-custom.css">

    <!-- TOASTR -->
    <link rel="stylesheet" href="~/Theme/beauty-spa/html/bower_components/toastr/toastr.min.css">

</head>

<body>

    <div class="page-wrapper" id="page-wrapper">

        @Html.Partial("_MenuAdmin")

        <main class="content">

            @Html.Partial("_HeaderAdmin")

            @RenderBody()

            @Html.Partial("_FooterAdmin")

        </main>

        <p class="text-success"></p>
        <div onload="javascript:void(0)" id="type-success"></div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/inputmask")
    @Scripts.Render("~/bundles/moneymask")

    @RenderSection("styles", required: false)
    @RenderSection("scripts", required: false)

    <!-- Common plugins -->
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/js/plugins/plugins.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/js/appUi-custom.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/chartjs/dist/chart.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/peity/jquery.peity.min.js"></script>
    <script src="~/Theme/admin-dashboardUi/html/lib/chartist/chartist.js"></script>
    <script src="~/Theme/admin-dashboardUi/html/lib/chartist/chartist-tooltip.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/js/widgets-custom.js"></script>

    <!-- jvectormap -->
    <script src="~/Theme/admin-dashboardUi/html/lib/vector-map/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="~/Theme/admin-dashboardUi/html/lib/vector-map/jquery-jvectormap-world-mill-en.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/js/dashboard.custom.js"></script>

    <!-- Data Tables -->
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/data-tables/responsive.bootstrap4.min.js"></script>
    <script src="~/Theme/admin-dashboardUi/html/js/plugins-custom/datatables-custom.js"></script>

    <!-- DATE PICKER -->
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/fullcalendar/moment.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/lib/dt-picker/jquery.datetimepicker.full.min.js"></script>
    <script type="text/javascript" src="~/Theme/admin-dashboardUi/html/js/plugins-custom/pickers-custom.js"></script>

    <!-- TOASTR -->
    <script type="text/javascript" src="~/Theme/beauty-spa/html/bower_components/toastr/toastr.min.js"></script>
    @*<script type="text/javascript" src="@Url.Content("~/Theme/assan-admin/js/toastr.init.js")"></script>*@
    <script type="text/javascript">
        $(document).ready(function ($) {
            @if (!string.IsNullOrEmpty(ViewBag.TypeToastr) && !string.IsNullOrEmpty(ViewBag.TitleToastr) && !string.IsNullOrEmpty(ViewBag.MessageToastr))
            {
                <text>
                    toastr_message("@ViewBag.TypeToastr", "@ViewBag.TitleToastr", "@ViewBag.MessageToastr");
                </text>
            }
        });

        function toastr_message(type, title, message) {
            toastr[type](message, title);
            //toastr['success'](message, title);
            //toastr.success("Message will come here", "Title");
        }
    </script>

</body>

</html>

LeilaoOnline/Views/Shared/_Menu.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="~/Theme/law-firm/html/images/logo.jpg" alt="" style="max-width:49px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#law-firm-navbar" aria-controls="law-firm-navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="law-firm-navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Leilao")">Leilões</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sobre</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contato</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Novidades</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto navbar-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link">@User.Identity.Name</a>
                    </li>
                    <li class="nav-item">
                        <a id="logout" class="nav-link" href="">Sair</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Login", "Home")">Entrar</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link" href="#">Cadastre um Leilão conosco</a>
                </li>
                <li class="nav-item">
                    <span class="nav-link"><i class="icon-phone-outgoing"></i> +55 31 9 9999-9999</span>
                </li>
            </ul>
        </div>
    </div>
</nav>