LeilaoOnline/Controllers/LanceController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using LeilaoOnline.Models;
using LeilaoOnline.Services;
using Microsoft.AspNet.Identity;

namespace LeilaoOnline.Controllers
{

    [Authorize(Roles = "Usuario")]
    public class LanceController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var lancesLeilao = _db.LancesLeilao.Include(l => l.Leilao).Include(l => l.Usuario);

            return View(lancesLeilao.ToList());
        }

        [Authorize(Roles = "Admin, Usuario")]
        public ActionResult List(Guid leilaoId)
        {
            var lancesLeilao = _db.LancesLeilao.Where(x => x.LeilaoId == leilaoId).OrderByDescending(x => x.Data).Include(l => l.Leilao).Include(l => l.Usuario);

            ViewBag.LeilaoId = leilaoId;

            return View(lancesLeilao.ToList());
        }

        public ActionResult Details(Guid id)
        {
            LanceLeilao lanceLeilao = _db.LancesLeilao.Find(id);

            if (lanceLeilao == null)
                return HttpNotFound();

            return View(lanceLeilao);
        }

        public ActionResult Create(Guid leilaoId)
        {
            string userId = User.Identity.GetUserId();

            LanceLeilao lance = new LanceLeilao
            {
                LeilaoId = leilaoId,
                UsuarioId = _db.Usuarios.Where(x => x.UserId == userId).FirstOrDefault().Id
            };

            return View(lance);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LanceLeilao lanceLeilao)
        {
            Leilao leilao = _db.Leiloes.Find(lanceLeilao.LeilaoId);

            LanceLeilao lance = _db.LancesLeilao.Where(x => x.LeilaoId == lanceLeilao.LeilaoId)
                                                .OrderByDescending(x => x.Valor)
                                                .FirstOrDefault();

            if (lance != null && lance.Valor >= lanceLeilao.Valor)
                ModelState.AddModelError("ValorMininoError", $"Valor Inferior ao último lance! Último Lance: R$ {lance.Valor}");
            if (lance == null && leilao.ValorInicial >= lanceLeilao.Valor)
                ModelState.AddModelError("ValorMininoError", $"Valor Inferior ao valor inicial! Lance Inicial: R$ {leilao.ValorInicial}");

            if (ModelState.IsValid)
            {
                lanceLeilao.Id = Guid.NewGuid();
                lanceLeilao.Data = GlobalManager.GetDateTimeNow();

                _db.LancesLeilao.Add(lanceLeilao);
                _db.SaveChanges();

                return RedirectToAction("List", new { leilaoId = lanceLeilao.LeilaoId });
            }

            return View(lanceLeilao);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LanceLeilao lanceLeilao = _db.LancesLeilao.Find(id);
            if (lanceLeilao == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeilaoId = new SelectList(_db.Leiloes, "Id", "Nome", lanceLeilao.LeilaoId);
            ViewBag.UsuarioId = new SelectList(_db.Usuarios, "Id", "Nome", lanceLeilao.UsuarioId);
            return View(lanceLeilao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LeilaoId,UsuarioId,Valor,Data")] LanceLeilao lanceLeilao)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(lanceLeilao).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LeilaoId = new SelectList(_db.Leiloes, "Id", "Nome", lanceLeilao.LeilaoId);
            ViewBag.UsuarioId = new SelectList(_db.Usuarios, "Id", "Nome", lanceLeilao.UsuarioId);
            return View(lanceLeilao);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LanceLeilao lanceLeilao = _db.LancesLeilao.Find(id);
            if (lanceLeilao == null)
            {
                return HttpNotFound();
            }
            return View(lanceLeilao);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            LanceLeilao lanceLeilao = _db.LancesLeilao.Find(id);
            _db.LancesLeilao.Remove(lanceLeilao);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeilaoOnline/Controllers/LeilaoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using LeilaoOnline.Models;

namespace LeilaoOnline.Controllers
{

    [Authorize]
    public class LeilaoController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var leiloes = _db.Leiloes.Include(l => l.Responsavel).Include(l => l.Status);

            return View(leiloes.ToList());
        }

        [Authorize(Roles = "Usuario")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leilao leilao = _db.Leiloes.Find(id);
            if (leilao == null)
            {
                return HttpNotFound();
            }
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome");
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome");

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,ValorInicial,Usado,DataAbertura,DataFim,ResponsavelId,StatusId")] Leilao leilao)
        {
            if (ModelState.IsValid)
            {
                leilao.Id = Guid.NewGuid();

                _db.Leiloes.Add(leilao);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome", leilao.ResponsavelId);
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome", leilao.StatusId);
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leilao leilao = _db.Leiloes.Find(id);
            if (leilao == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome", leilao.ResponsavelId);
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome", leilao.StatusId);
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,ValorInicial,Usado,DataAbertura,DataFim,ResponsavelId,StatusId")] Leilao leilao)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(leilao).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ResponsavelId = new SelectList(_db.Usuarios, "Id", "Nome", leilao.ResponsavelId);
            ViewBag.StatusId = new SelectList(_db.StatusesLeilao, "Id", "Nome", leilao.StatusId);
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Leilao leilao = _db.Leiloes.Find(id);
            if (leilao == null)
            {
                return HttpNotFound();
            }
            return View(leilao);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Leilao leilao = _db.Leiloes.Find(id);
            _db.Leiloes.Remove(leilao);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeilaoOnline/Views/Leilao/Create.cshtml
@model LeilaoOnline.Models.Leilao

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leilao</h4>
        <hr />
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorInicial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorInicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorInicial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Usado)
                    @Html.ValidationMessageFor(model => model.Usado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataAbertura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataAbertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataAbertura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataFim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataFim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataFim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsavelId, "ResponsavelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResponsavelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResponsavelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeilaoOnline/Views/Leilao/Delete.cshtml
@model LeilaoOnline.Models.Leilao

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leilao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Responsavel.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Responsavel.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataAbertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAbertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFim)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LeilaoOnline/Views/Leilao/Details.cshtml
@model LeilaoOnline.Models.Leilao

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Leilao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Responsavel.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Responsavel.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataAbertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAbertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFim)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LeilaoOnline/Views/Leilao/Edit.cshtml
@model LeilaoOnline.Models.Leilao

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leilao</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorInicial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorInicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorInicial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Usado)
                    @Html.ValidationMessageFor(model => model.Usado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataAbertura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataAbertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataAbertura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataFim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataFim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataFim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsavelId, "ResponsavelId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResponsavelId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResponsavelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeilaoOnline/Views/Leilao/Index.cshtml
@model IEnumerable<LeilaoOnline.Models.Leilao>
@using LeilaoOnline.Models

@{
    ViewBag.Title = "Leilões";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper" id="page-wrapper">
    <main class="content">

        <div class="page-subheader">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="list">
                            <div class="list-item pl-0">
                                <div class="list-thumb ml-0 mr-3 pr-3  b-r text-muted">
                                    <i class="icon-Box-Close"></i>
                                </div>
                                <div class="list-body">
                                    <div class="list-title fs-2x">
                                        <h3>@ViewBag.Title</h3>
                                    </div>
                                </div>
                                @if (User.IsInRole("Admin"))
                                {
                                    <a href="@Url.Action("Create")" class="btn btn-icon btn-primary btn-sm">
                                        <i class="fa fa-plus"></i>
                                        Novo
                                    </a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="bg-white table-responsive rounded shadow-sm pt-3 pb-3 mb-30">
            <table id="data-table" class="table table-striped table-responsive-sm" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Responsável</th>
                        <th>Status</th>
                        <th>Nome</th>
                        <th>Valor Inicial</th>
                        <th>Usado</th>
                        <th>Data Abertura</th>
                        <th>Data Fim</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="vertical-align: middle;">
                                @Html.DisplayFor(modelItem => item.Responsavel.Nome)
                            </td>
                            <td style="vertical-align: middle;">
                                @if (item.StatusId == new Guid("FCA13C60-89E9-4D1C-9A80-EB366FA2F4D5")) //Rascunho
                                {
                                    <span class="badge badge-text badge-light mr-2 mb-2" data-id="@item.StatusId">@item.Status.Nome</span>
                                }
                                else if (item.StatusId == new Guid("91D8BC5F-06E4-48F1-BA48-CDF609F0D94C")) //Aprovado
                                {
                                    <span class="badge badge-text badge-primary mr-2 mb-2" data-id="@item.StatusId">@item.Status.Nome</span>
                                }
                                else if (item.StatusId == new Guid("F0FD43EB-001E-4DE8-9C93-0D92A4AE0B21")) //Ganho
                                {
                                    <span class="badge badge-text badge-success mr-2 mb-2" data-id="@item.StatusId">@item.Status.Nome</span>
                                }
                                else if (item.StatusId == new Guid("AAA59E0E-9CAE-4124-82D0-EEBA84E71423")) //Perdido
                                {
                                    <span class="badge badge-text badge-danger mr-2 mb-2" data-id="@item.StatusId">@item.Status.Nome</span>
                                }
                                else if (item.StatusId == new Guid("D736FF75-5152-45C0-BAAA-23802B3942EC")) //Cancelado
                                {
                                    <span class="badge badge-text badge-warning mr-2 mb-2" data-id="@item.StatusId">@item.Status.Nome</span>
                                }
                            </td>
                            <td style="vertical-align: middle;">
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                            <td style="vertical-align: middle;">
                                @Html.DisplayFor(modelItem => item.ValorInicial)
                            </td>
                            <td style="vertical-align: middle;">
                                @Html.DisplayFor(modelItem => item.Usado)
                            </td>
                            <td style="vertical-align: middle;">
                                @Html.DisplayFor(modelItem => item.DataAbertura)
                            </td>
                            <td style="vertical-align: middle;">
                                @Html.DisplayFor(modelItem => item.DataFim)
                            </td>
                            <td style="vertical-align: middle;">
                                <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-info btn-sm mr-2 mb-2">
                                    <i class="fa fa-eye"></i>
                                </a>

                                @if (User.IsInRole("Admin"))
                                {
                                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-warning btn-sm mr-2 mb-2">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a href="@Url.Action("Delete", new { id = item.Id })" class="btn-o btn-danger btn-sm mr-2 mb-2">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                }
                                @if (User.IsInRole("Usuario") && item.StatusId == new Guid("4df2f05b-1a14-42f4-91ad-c6c13a0bfea3"))
                                {
                                    <a href="@Url.Action( "Create", "Lance", new { leilaoId = item.Id })" class="btn btn-danger btn-sm mr-2 mb-2">
                                        <i class="fa fa-handshake-o"></i>
                                    </a>
                                }

                                <a href="@Url.Action( "List", "Lance", new { leilaoId = item.Id })" class="btn btn-success btn-sm mr-2 mb-2">
                                    <i class="fa fa-bars"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </main>
</div>